### ISSUE TITLE
Cannot open file '/tmp

### ISSUE THREAD

**Issue by wenkui123** [ncbi/amr#106]
Hello,
I want to use AMRFinderPlus in docker container , , but I get the following error:

root@38d842152c2e:/amrfinder# ./amrfinder -u
Running: ./amrfinder -u
Software directory: '/amrfinder/'
Software version: 3.11.2

*** ERROR ***
Reading file '/tmp/amrfinder.yz1fUh/log'
Cannot open file '/tmp/amrfinder.yz1fUh/log'

HOSTNAME: 38d842152c2e
SHELL: ?
PWD: /amrfinder
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/amrfinder
Progam name:  amrfinder
Command line: ./amrfinder -u

Why does this error occu ?  How can I solve this problem?
thanks

**Comment by evolarjun** [comment]
Hi @wenkui123 ,

I haven't been able to reproduce your issue, perhaps there is an additional restriction on /tmp or growing the container in your docker environment? I will continue to investigate.

However you shouldn't need to run `amrfinder -u` if you're using the latest image (right now  tag 3.11.2-2022-12-19.1) because we update the container with the latest software and database on every release.  If you want to use it in non-interactive mode here's an example of how we suggest using it:

```
# Example run on a local file with 8 threads
docker run --rm -v ${PWD}:/data ncbi/amr amrfinder -p test_prot.fa --threads 8
```

I just realized we don't have any documentation about how to use the docker container in [our documentation](/ncbi/amr/wiki). We'll work on that. 

Let us know if you can run AMRFinderPlus on an external sequence. I will continue trying to figure out what's going wrong in your case.
