### ISSUE TITLE
GFF file

### ISSUE THREAD

**Issue by meg256** [ncbi/amr#135]
I'm running 3.11.26. Trying to run protein search with gff:
```
amrfinder -p renamed_faa.faa -g renamed_annotations.gff --plus
```

But keep getting this error:

```
*** ERROR ***
gff_check.cpp: Protein FASTA id "1097_1" is not in the GFF file
```
However, I confirmed that this particular ID is in fact in both files:
![image](https://github.com/ncbi/amr/assets/84437436/b13ca5c0-c602-413b-8cbd-564917041ae8)

If I delete 1097_1 from my faa, the next sequence in alphanumeric order will throw an error too, and so on if I remove that (1097_10, then 1097_11, etc)

I also tried running in 3.10.46 and had the same issue.

Here are a modified version of my original faa and gff:
[amrfinder.zip](https://github.com/ncbi/amr/files/13892077/amrfinder.zip)

Thanks for any help you can offer!

**Comment by vbrover** [comment]
This GFF file does not follow the standard https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md.
For example, strand should by "-" or "+".

I see the annotation was done by Prodigal.
Could you post the original Prodigal output?

**Comment by evolarjun** [comment]
Hi,

I took a look at your files and it looks from the "Prodigal" fields in the GFF file the annotation is from Prodigal. We have an "annotation_format" that should process prodigal output files (see [our documentation for the --annotation_format <format> option](https://github.com/ncbi/amr/wiki/Running-AMRFinderPlus#the---annotation_format-format-option)), however it looks like there is something else going on with your example that AMRFinderPlus is choking on, we're going to have to investigate further to figure out what is going on. 

There is also an issue of protein sequences with large numbers of X's which AMRFinderPlus is also having a problem with.  I'm curious as to what you're doing that you end up with protein sequences with lots of ambiguous characters? Is that something we should work on handling? I haven't encountered that in the usual sources of input files for AMRFinderPlus. What is the source of input that produces annotations with lots of ambiguous amino-acids?

Sorry things aren't working for you. I'll continue to investigate how I can get your example working, but since this appears unlike input we've encountered before, could you elaborate on what you're trying to do with AMRFinderPlus?

Thanks and I'll let you know what we figure out,
Arjun

**Comment by evolarjun** [comment]
I thought I would mention that, as Slava described above, it looks like the problem is caused by the '+' and '-' in the strand column of the GFF.  Please let us know if you are still having issues.

**Comment by evolarjun** [comment]
We will work to make the error message a bit clearer in the next version of AMRFinderPlus.
