### ISSUE TITLE
NG_nnnnnn accession numbers missing version

### ISSUE THREAD

**Issue by tseemann** [ncbi/amr#14]
In `AMR_CDS` and some other files it is just `NG_047055`

```
>446950888|WP_001028144.1|NG_047055|1|2|aac(6')-Ie|aac(6')-Ie|
bifunctional_aminoglycoside_N-acetyltransferase_AAC(6')-Ie/aminoglycoside_O-phosphotransferase_APH(2'')-Ia 
NG_047055:101-1540
```

But in `ReferenceGeneCatalog.txt` is is `NG_047055.1`

**Comment by evolarjun** [comment]
We generally link via the protein accession, (WP_001028144.1 in your example), but I can see we're inconsistent with the nucleotide accessions; the NG_ records don't have a version, but the GenBank accessions do.  For the purposes of our database protein sequences are primary, so we usually link via protein sequence/accession. We'll make things consistent in a future release.

**Comment by evolarjun** [comment]
Yes, that's what I meant when I said "inconsistent". I had missed this previously because our internal use of AMR_CDS is limited. We'll get this fixed so the '.version' is included for our next database release.

**Comment by tseemann** [comment]
Thanks @evolarjun

**Comment by evolarjun** [comment]
@tseemann  This should be fixed in the latest release of the database (2019-10-30.1) Note that the FTP site paths have changed so the software will not break by updating to backwards incompatible database versions. The new site is at https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/latest/

I hadn't mentioned before that the [Reference Gene Catalog](https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/latest/ReferenceGeneCatalog.txt) is made for external consumption, and should have the data you need.  It also has a [Web interface](https://www.ncbi.nlm.nih.gov/pathogens/isolates#/refgene/). New documentation for ReferenceGeneCatalog.txt [is here](https://github.com/ncbi/amr/wiki/AMRFinderPlus-database#referencegenecatalogtxt).

We have a new version of AMRFinderPlus (3.2.1) compatible with this database that I encourage you to try out and let us know what issues you find. Your feedback is (_almost_) always appreciated. ;-)

Thanks again.

**Comment by tseemann** [comment]
I look forward to annoy^H^H^H^Hhelping you in the future.
