### ISSUE TITLE
PackagesNotFoundError

### ISSUE THREAD

**Issue by fredotter** [ncbi/amr#157]
Hi,
I'm starting to learn how to use AMRFinder, but I'm unsure how to solve this problem. Whenever I try to install the AMRfinder with all of the bioconda environment prerequisites, it always gives this output. I tried one of the solution from (https://bioinformatics.stackexchange.com/questions/22229/arm64-installation-of-amrfinderplus), but it doesn't seem to work either. Does anyone know how to solve it? Thanks in advance!

<img width="1038" alt="Screenshot 2024-11-20 at 13 21 55" src="https://github.com/user-attachments/assets/236d6389-eb5c-475c-9790-e3b68e3d154c">

**Comment by vbrover** [comment]
If you can run `blastp` and `hmmsearch`, you can install `amrfinder` directly from `github.com`.

**Comment by evolarjun** [comment]
Hi @fredotter ,

AMRFinderPlus compiles fine for ARM, and the dependencies all are available for arm (BLAST+, HMMER, libcurl), however to my knowledgethey still don't all have conda packages for ARM.   What that means is that you can manually install AMRFinderPlus and its dependencies outside of the conda package. It's fairly easy depending on you operating system because there are usually OS packages for most of what you need. See https://github.com/ncbi/amr/wiki/Compile-from-source for the instructions. 

I don't know what operating system you're using, but on a fresh ARM VM with ubuntu 22.04 the following worked for me:

```
sudo apt-get update

# Install blast, libcurl and tools to help build the software
sudo apt-get install  ncbi-blast+ git libcurl4-openssl-dev build-essential curl

#  Install HMMER because an arm apt package doesn't seem to be available yet
wget http://eddylab.org/software/hmmer/hmmer-3.4.tar.gz
tar xf hmmer-3.4.tar.gz
cd hmmer-3.4
./configure
make
make check
sudo make install

# Install AMRFinderPlus
cd ~
git clone https://github.com/ncbi/amr.git
cd amr
git submodule update --init
make
sudo make install
sudo amrfinder -u
./test_amrfinder.sh path
```

I'm not sure how https://bioinformatics.stackexchange.com/questions/22229/arm64-installation-of-amrfinderplus got an arm version of the conda package for blast, but I couldn't find it.

**Comment by fredotter** [comment]
Thankyou all for the quick response, it seems to be working now!
