### ISSUE TITLE
amrfinder dosen't report gene aac(6')-Iaa

### ISSUE THREAD

**Issue by chen1i6c04** [ncbi/amr#158]
Hi 

I found `amrfinder` won't report gene aac(6')-Iaa, but `resfinder` will.

In the [Reference Gene Catalog](https://www.ncbi.nlm.nih.gov/pathogens/refgene/#aac(6')-Iaa), scope of aac(6')-Iaa is `non-reported`
Is that the reason? What dose `non-reported` mean?

Thanks

**Comment by feldgard** [comment]
Hi,

AMRFinderPlus does not report aac(6')-Iaa because it does not confer a resistance phenotype unless an expression mutant is constructed (https://pubmed.ncbi.nlm.nih.gov/10542165/). This gene is part of a family that also includes the nearly identical aac(6')-Iy and can be identified with the HMM model [NF000140.3](https://www.ncbi.nlm.nih.gov/pathogens/hmm/#hmm_accession:NF000140.3). It is thought these genes might be involved in sugar catabolism, given their proximity to other sugar catabolism genes, but their function is uncertain.

Consequently, we do not report these in AMRFinderPlus as they are non-indicative of phenotype, and so are flagged as `non-reported` to indicate this status. These proteins are included in the Reference Gene Catalog for completeness, however.

Best,

Mike Feldgarden, NCBI

**Comment by evolarjun** [comment]
I would add that those genes (aac(6')-Iaa and aac(6')-Iy) are chromosomal and ubiquitous (or nearly ubiquitous) in _Salmonella_ so it is especially not helpful to be reporting an aminoglycoside resistance gene for all _Salmonella_. I'm not sure how ResFinder gets around that.

@chen1i6c04 I'm going to close this ticket as solved, but please reopen and let us know if there's anything you don't understand.

Thanks,
Arjun
