### ISSUE TITLE
Include the sample/input file name on each line of the output

### ISSUE THREAD

**Issue by flashton2003** [ncbi/amr#25]
Hello,

It would be really helpful uf you could include the sample/input file name on each line of the output, to make it straightforward to combine the output of multiple runs into a single file.

Thanks,

Phil

**Comment by evolarjun** [comment]
Hi Phil,

You may be right. I usually process the results to prepend with a `sed "s/^/$sample\t/'`. 

e.g: 
```
amrfinder -p $sample.faa -n $sample.fna -g $sample.gff | sed "s/^/$sample\t/" > $sample.amrfinder
```

Prepending the filename could eliminate that, but a big part of why I haven't pushed for that is the decision of which filename prepend? There can be 3: `--nucleotide`, `--protein`, and `--gff`.

The other option would be to offer a command-line option to prepend a sample name column e.g.: `--samplename <sample>` to add a column with that text to the beginning, but until now I felt like that's a bit of feeping creatureism. I could be convinced otherwise.

Arjun

**Comment by flashton2003** [comment]
Hi Arjun,

Thanks for the quick response. IMHO, I don't think a `--samplename` flag would be over-board, as maybe some of the intended users of amrfinder might not be sed literate? But, up to you.

Thanks,

Phil

**Comment by azat-badretdin** [comment]
`grep "" *blah > big.blah`

**Comment by evolarjun** [comment]
Hi Phil,

Thanks, I think you've convinced me. I'll discuss it with the team, but you're right that even though there are a bunch of ways to do it with shell commands there are also a bunch of people who don't know them. (Thanks @azat-badretdin I hadn't thought of that one.) 

Arjun

**Comment by flashton2003** [comment]
Ok, thanks Arjun!

**Comment by evolarjun** [comment]
With [release version 3.8.28](https://github.com/ncbi/amr/releases/tag/amrfinder_v3.8.28) we finally added a `--name` option to prepend an identifier to every row of the results.

**Comment by flashton2003** [comment]
thank you!
