### ISSUE TITLE
It is possible to customize the database?

### ISSUE THREAD

**Issue by giuferrero** [ncbi/amr#28]
Hi,
Recently, I used AMRFinder+ for my analysis of antibiotic resistance prediction of bacterial WGS data. I found the tool very useful and efficient. I compared it with the mykrobe predictor tools found similar performance on Staphylococcus aureus datasets. 

However, in order to improve the analysis, I need to add other annotations of mobile element and gene variants that are lacking in the current version of the AMRFinder+ database. In particular, some features used by mykrobe are lacking in the database.

It is possible to customize the reference database used by AMRFinder+ in order to add these annotations?

Thank you very much.

Best regards,
Ferrero Giulio

**Comment by evolarjun** [comment]
Hi Ferrero,

Thanks for your kind words.  

Yes it absolutely is possible to customize the reference database. The database is made up of plain text files in simple FASTA, tab-delimited, and HMMER formats. However to the best of my knowledge we haven't had anyone outside our group try customizing the database, and for that reason the process may not be as smooth as we would like.

The previous paragraph was meant as a bit of a disclaimer. But as I said the file formats themselves are pretty simple, and we would appreciate hearing about your experience. Information on the database and file formats is on [the wiki](https://github.com/ncbi/amr/wiki/AMRFinderPlus-database). 

Since we come out with database updates on a semi-regular basis, if you're potentially interested in updates I suggest being ready to use version control, diff and patch, or some other method to allow you to merge updates more easily.

You've piqued my interest though, if it isn't revealing too much, what is it that you need from Mycrobe and want to add? We have had intentions to add M. tb support for some time, but haven't had yet had the free cycles to do it.

Arjun

**Comment by giuferrero** [comment]
Thank you for your answer.
I want to add to the DB some S aurues mutations of fusA, grlA, grlB, and rpoB and some genes which are present in the Mykrobe DB but I didn't found in the AMRFinder+ DB. If you want I can send you the list if it can be useful.
Bests,
Giulio

**Comment by evolarjun** [comment]
Hi Giulio,

With the 2020-03-20.1 release of the database we added quite a few [Staph aureus mutations](https://www.ncbi.nlm.nih.gov/pathogens/isolates#/refgene/whitelisted_taxa:Staphylococcus_aureus%20AND%20(gene_family:parC%20OR%20gene_family:fusA%20OR%20gene_family:gyrA%20OR%20gene_family:rpoB)) in the genes you listed. Is there a set we're missing? What Staph aureus genes do you think we should be including?

Don't forget that you need to use the `--organism=Staphylococcus_aureus` option to get mutation detection for Staph aureus.

New protein point mutations go in AMRProt and AMRProt-mutation.tab, New nucleotide point mutations go in AMR_DNA-<organism> and AMR_DNA-<organism>.tab. 

New protein sequences need to go in AMRProt, fam.tab, and new HMMs in AMR.LIB and fam.tab.
 
The file format descriptions are in the wiki (https://github.com/ncbi/amr/wiki/AMRFinderPlus-database#file-formats). Let us know if you have any questions and/or how we can improve the documentation.

**Comment by giuferrero** [comment]
Thank you very much for your indication. I'm using the option --organism=Staphylococcus_aureus and it works perfectly.

However, I didn't found these variants in your DB (which are present in mykrobe): 
fusA_A376V 	FusidicAcid
fusA_A67T 	FusidicAcid
fusA_A70V 	FusidicAcid
fusA_A71V 	FusidicAcid
fusA_D373N 	FusidicAcid
fusA_D387I 	FusidicAcid
fusA_E468V 	FusidicAcid
fusA_H557Y 	FusidicAcid
fusA_I449K 	FusidicAcid
fusA_P161I 	FusidicAcid
fusA_R76C 	FusidicAcid
fusA_T326I 	FusidicAcid
fusA_T441Y 	FusidicAcid
fusA_V607I 	FusidicAcid
grlA_A48T 	Ciprofloxacin
grlA_D432G 	Ciprofloxacin
grlA_D79V 	Ciprofloxacin
grlA_S108N 	Ciprofloxacin
grlA_V41G 	Ciprofloxacin
grlB_E432H 	Ciprofloxacin
grlB_E432N 	Ciprofloxacin
grlB_E432V 	Ciprofloxacin
grlB_G443E 	Ciprofloxacin
grlB_I451S 	Ciprofloxacin
grlB_M585S 	Ciprofloxacin
grlB_R444S 	Ciprofloxacin
gyrA_E88V 	Ciprofloxacin
rpoB_A565R 	Rifampicin
rpoB_Q468L 	Rifampicin
rpoB_Q468R 	Rifampicin
rpoB_S456K 	Rifampicin

Furthermore, these are genes tested in mykrobe that I didn't found in the DB:
IsaB	Clindamycin
lnuA	Clindamycin
lnuB	Clindamycin
aacAaphD	Gentamicin

I hope this should help to improve your tool that I found very useful.
Bests,
Giulio

**Comment by evolarjun** [comment]
Hi Giulio,

Thanks for posting that. We'll take a look at the list and see if the new ones meet our standards for curating into the database. 

If you do end up adding mutations or genes to the AMRFinderPlus database let us know how it goes. 

Arjun

**Comment by giuferrero** [comment]
Hi,
I added both mutations and genes and it works perfectly.
Thanks for your support.
Bests,
Giulio

**Comment by giuferrero** [comment]
Unfortunately, on some samples the program crashed with this error:

"alignment.cpp", line 334: reference. substr (head, mut. reference. size ()) == mut. reference

Can I change something to solve it?
Bests,
Giulio

**Comment by evolarjun** [comment]
Hi Giulio,

We hadn't hit that error message because the QC checks our database goes
through before being written in AMRFinderPlus format prevent us from reaching
that branch of the code. This is part of a database consistency check that the allele
in the reference sequence FASTA matches the reference allele for the mutation.
E.g.: There's an A at site 345 of gene ABC, but the point mutation definition
looks like ABC_Y345T.

The error message was used in developing the software so it is more about the
internals of the software than the database. In the very near future we're
planning to release a new version of the software (with a slightly modified
database format) with a much improved error message pointing out what
mutation has the issue.

----

We've also taken a closer look at the list of genes and mutations you provided.

The four genes you list are actually already in the database:
- IsaB Clindamycin - appears to be a typo in Mycrobe (A mix-up between upper case i and lower case L).  WP_011133547.1 lsa(B) is in our database
- lnuA Clindamycin - is in the AMRFinderPlus database as WP_063851340.1 lnu(A)
- lnuB Clindamycin - is in the AMRFinderPlus database as WP_032495568.1 lnu(B)
- aacAaphD Gentamicin - is a fusion gene in the AMRFinderPlus database as WP_001028144.1 aac(6')-Ie/aph(2'')-Ia bifunctional

The mutations you listed fall in a few categories:
- Some appear to be compensatory: fusA_A376V, fusA_A70V, fusA_A71V, fusA_R76C. Even though they are biologically interesting, we have not included these as these do not directly confer a phenotype, and we do not want our high-throughput users to mistakenly assume these confer a resistance phenotype.
- Some we will add, and we appreciate you informing us about them: fusA_I449K (this is an E449, not I), fusA_V607I, parC_D432G (grlA), parC_S108N (grlA), rpoB_Q468L, rpoB_Q468R.
- The remainder are either mutations that have been observed only in co-occurrence with other, known resistance mutations (e.g., parE/grlB_I451S), or that we could not find support for in the literature and also which might be errors (e.g., parE/grlB_M585S when there is a P585S mutation described).

We are just about ready to do a new database release, and these new mutations won't make it into that release, but they should be in our next one.

Arjun

**Comment by giuferrero** [comment]
Ok, perfect, I check and correct the error in one mutation. 
Thanks you very much Arjun for your help.
Bests,
Giulio

**Comment by evolarjun** [comment]
We just released a new version of the software [AMRFinderPlus 3.8.4](https://github.com/ncbi/amr/releases/tag/amrfinder_v3.8.4), and it includes a more informative error message. Let us know if that works for you.

**Comment by giuferrero** [comment]
Thanks Arjun, I'm running it on all my samples and it works perfectly.
Best regards,
Giulio

**Comment by evolarjun** [comment]
Great! 

I'll leave this issue open until we come out with a release including the additional Staph point mutations. We'll also be adding a few Staph virulence genes.

**Comment by evolarjun** [comment]
We added _Staph aureus_ point mutations in database release 2020-06-11.1.
