### ISSUE TITLE
how to get resistance drug infomation from amrfinder result？

### ISSUE THREAD

**Issue by feihongloveworld** [ncbi/amr#31]
hi sir：
    i run amrfinderplus and got gene result file；how can i get drug informations for these resistance genes in easy way ？
thanks

**Comment by evolarjun** [comment]
Resistance categories are in the Class and Subclass columns of the output (column 11 and 12).

See the [Class and Subclass section](https://github.com/ncbi/amr/wiki/Interpreting-results#class-and-subclass) of the documentation for a short description of what goes into those columns.

**Comment by feihongloveworld** [comment]
hi sir:
     is mean that subclass is better than class when  i  want to Compare AST result with amrfinderpu result？

**Comment by evolarjun** [comment]
Subclass is more specific when more specific information is available.  Most likely that is the field you will want to compare AST data to since AST information will be for a specific drug. 

Note, however, that subclass can be broad for genes where we have not found more specific experimental results.  Also not all drugs have been tested against all genes, so in some cases gene-mediated resistance may be broader than the subclass indicates.
