### ISSUE TITLE
Add option for output without column names

### ISSUE THREAD

**Issue by jdmccauley** [ncbi/amr#40]
Hi amr team,

I'm using this tool for nucleotide fasta files in bulk, and I want to compile them into a single output file. My current solution  to compile them in bash is this:
```
for file in *.fa
    do
        amrfinder -n $file -q >> my_results.tsv
    done
```
This works, except the append of the output from each loop iteration includes the column names. So my resulting tsv has a line of column names every other line. Can you add an option to the amrfinder command that doesn't include the column names? This would make it much easier to process many files in bulk.

Best,
Josh

**Comment by jdmccauley** [comment]
I found a temporary solution by adding column names to a file, and then adding trimmed output to that file:

```
echo "Protein identifier        Contig id       Start   Stop    Strand  Gene symbol     Sequence name   Scope   Element type    Element subtype Class   Subclass        Method  Target length   Reference sequence length       % Coverage of reference sequence        % Identity to reference sequence        Alignment length        Accession of closest sequence   Name of closest sequence        HMM id  HMM description" > my_results.tsv

for file in *.fa
    do
        amrfinder -n $file -q | grep -v Protein | tail +1 | my_results.tsv
    done
```

This works for now, but adding the option to not include column names would be awesome!

**Comment by evolarjun** [comment]
Hi Josh, 

Thanks for your question. This is something that I do all the time. 

We have a couple of hints on our "[Tips and tricks page](https://github.com/ncbi/amr/wiki/Tips-and-tricks#combine-mutliple-amrfinderplus-output-files-prepending-each-line-with-the-filename)" when put together can do this, but your way works too. 

Since removing the field names is as easy as adding `| grep -v '^Protein identifier'` or `| awk 'NR>1{print}'` or `| tail -n +2` or any of a number of other options I'm not sure how essential that is. 

Usually I like to have a separate file for each assembly in case I need to re-run one for any reason, then I combine them afterwards.  For example by combining two of our tricks from [the tricks page](https://github.com/ncbi/amr/wiki/Tips-and-tricks):

```
#!/bin/bash

for assembly in *.fa
do
    base=$(basename $assembly .fa)
    amrfinder -n $assembly --threads 8 --plus > $base.amrfinder
done

h=$(head -1 $(ls *.amrfinder | head -1))
echo $'filename\t' "$h" > combined.tsv
grep -v '^Protein identifier' *.amrfinder | sed 's/\.amrfinder:/\t/'   >> combined.tsv
```

The above uses a couple of bashisms so you'll have to modify it slightly if you're using another shell. Since this combination of tricks is likely something people other than you and I want to do I'll add this to that page.

**Comment by evolarjun** [comment]
I just added the above script to our Tips and tricks page: [Combine the above two tricks to run AMRFinderPlus on a series of files and combine the results](https://github.com/ncbi/amr/wiki/Tips-and-tricks#combine-the-above-two-tricks-to-run-amrfinderplus-on-a-series-of-files-and-combine-the-results)

Let us know if you have any other issues.

**Comment by jdmccauley** [comment]
Hi Arjun,

Thanks for getting back to me so quickly. I wasn't aware of the 'Tips and Tricks' page, so I'll check it out and thanks for adding my issue to that.

Best,
Josh
