### ISSUE TITLE
redundant gff files

### ISSUE THREAD

**Issue by ShresthaRima** [ncbi/amr#49]
@evolarjun @kmt @slottad @nawrockie 

[aa.giff.txt](https://github.com/ncbi/amr/files/6012736/aa.giff.txt)
Hi!
I ran the code:

amrfinder -n for_amrfinder.fna -g aa.giff -O Klebsiella

and received the below error:

*** ERROR ***
Parameter --gff is redundant

The attached .txt file is aa.giff file (glimpse only). As the original .gff was from PROKKA, I changed them into the amr .giff format as per instruction at #24 and tutorial.

I could not figure out what should not be redundant in the .giff file. I see the first column with the same name.
I, being, sufficient user of linux, look forward for the solution.
thanks

**Comment by vbrover** [comment]
A `.gff` file is needed to link the protein FASTA and DNA FASTA files.
Since there is no protein FASTA file, the `.gff` file will not be used.

**Comment by evolarjun** [comment]
Hi Rima,

Thanks for trying AMRFinderPlus. When you only use the assembly (nucleotide) file, as Slava mentioned above, you don't need to include a GFF because AMRFinderPlus can figure out coordinates from the nucleotide file. If you just remove `-g aa.giff` from the command-line AMRFinderPlus should run. 

However, since you already have a Prokka  annotation, we would recommend you run AMRFinderPlus in the full "combined" nucleotide plus protein mode. That enables AMRFinderPlus to use HMMs to enhance sensitivity for novel AMR genes.  If you want to run in combined mode you would need to include the nucleotide and GFF files (which you have used above) as well as the protein FASTA file from Prokka's output.

You would run it something like the following (I called the protein FASTA `protein.fa`)
```
amrfinder -p protein.fa -n for_amrfinder.fna -g aa.giff -O Klebsiella
```

Please let us know if you have further issues.

Arjun

**Comment by ShresthaRima** [comment]
Thank you @evolarjun and @vbrover. It did solved the problem.
