### ISSUE TITLE
Cannot download any databases using amrfinder -u

### ISSUE THREAD

**Issue by padpadpadpad** [ncbi/amr#57]
Hi all

Successfully downloaded `ncbi-amrfinderplus` into its own conda environment, but when I run `amrfinder -u` I receive the error:

`*** ERROR ***

Cannot create directory "/home2"`

Complete output is attached.

Any thoughts let me know. I think it could be to do with permissions given I do not have admin rights, but I can easily download things onto my area of the server.

Cheers
Dan
![Screen Shot 2021-07-05 at 21 18 24](https://user-images.githubusercontent.com/10220722/124515180-af605d00-ddd6-11eb-8f4f-b5ee29d298c1.png)

**Comment by vbrover** [comment]
Could you create the directory `/home2/ISAD/dp415/miniconda3/envs/amr_env/share/amrfinderplus/data` manually and then run `amrfinder -u`?

Also, what exit code does this command return: `ls /home2`?

**Comment by padpadpadpad** [comment]
I have created the directory manually but the error remains after re-running the command

`ls /home2` gives the error `ls: cannot open directory '/home2': Permission denied`.

I do not have access until `/home2/ISAD/dp415`.

**Comment by vbrover** [comment]
Could you post your screen output after `amrfinder -u`?

**Comment by padpadpadpad** [comment]
It remains the same as in my first post (hopefully there is a screenshot on the original post).

**Comment by vbrover** [comment]
The first post said that the directory 

    /home2/ISAD/dp415/miniconda3/envs/amr_env/share/amrfinderplus/data

could not be created.
Now that you have created this directory manually, there should be another error about failing to create the directory 

    /home2/ISAD/dp415/miniconda3/envs/amr_env/share/amrfinderplus/data/2021-06-01.1

`amrfinder_update` of this version will fail because your `/home2` is not readable (this is our bug which we will fix in a future `amrfinder` version).
My idea to circumvent this bug is to create the needed directories manually.

**Comment by padpadpadpad** [comment]
Thanks

I tried to make the next directory `/home2/ISAD/dp415/miniconda3/envs/amr_env/share/amrfinderplus/data/2021-06-01.1`.

I then attempted `amrfinder -u` and did receive a new error (screenshot attached). Is there anyway to manually download the database and tell amrfinder to use that?

![Screen Shot 2021-07-07 at 15 34 40](https://user-images.githubusercontent.com/10220722/124778708-139b3200-df39-11eb-99b6-ae33e200c7c7.png)

**Comment by vbrover** [comment]
Please try:

    amrfinder -U

(Capital "U")

**Comment by padpadpadpad** [comment]
This works. Should I have been doing that all the time.

Thank you very much.

**Comment by vbrover** [comment]
`amrfinder -U` does not check the existing version and forces updating the data files.

You have downloaded the most recent data files.
The next version data files will most likely come with the updated software where this bug will be fixed.
So that you will be able to use the regular `amrfinder -u` without hacks.

**Comment by evolarjun** [comment]
We just made a release [version 3.10.11](https://github.com/ncbi/amr/releases/tag/amrfinder_v3.10.11) that should address this issue. It may take a while to percolate through bioconda.
