### ISSUE TITLE
cutoff value

### ISSUE THREAD

**Issue by Galal-M** [ncbi/amr#59]
Hi everyone
sorry my question may looks silly
could anyone tell what is the cutoff used as default in AMRFinder plus ? If I want to use cutoff value less than the default how to add it to the command
I tried with the following command but I got an error 
amrfinder --plus -p Aminoacids.Fasta -O Streptococcus --ident_min 0-1
*** ERROR ***
Cannot convert "ident_min" to number

I used the command for nucleotide and got the same error as well

thank you in advanced

**Comment by vbrover** [comment]
$ amrfinder --help
    ....
    -i MIN_IDENT, --ident_min MIN_IDENT
        Minimum proportion of identical amino acids in alignment for hit (0..1). -1 means use a curated threshold if it exists and 0.9 otherwise
        Default: -1
    -c MIN_COV, --coverage_min MIN_COV
        Minimum coverage of the reference protein (0..1)
        Default: 0.5
    ...

To use the identity cutoff of 50% run

    amrfinder --ident_min 0.5

**Comment by Galal-M** [comment]
thank you @vbrover

**Comment by evolarjun** [comment]
Hi Galal-M,

Just to be clear by default AMRFinderPlus uses multiple different blast and HMMer score cutoffs.  AMRFinderPlus doesn't work like many of the other systems because it uses both a hierarchy of HMMs with curated score cutoffs and some manually assigned and some default blast cutoffs. 

We primarily use the `--ident_min` and `--coverage_min` options for testing, but results won't be the same as a purely blast-cutoff based system because of the hierarchical arrangement of families and HMMs.  We've tuned AMRFinderPlus as well as we can to give accurate results. The goal is for it to provide an affirmative identification of a gene, rather than what gene is most similar. 

I'm not sure of your application, but if there are gene calls you think we're getting incorrect or missing, please let us know.
