### ISSUE TITLE
amr_report -version prints a blank line

### ISSUE THREAD

**Issue by tseemann** [ncbi/amr#6]
Same is true for `amrfinder`. Installed via conda
```
% amr_report
Report AMR proteins
HELP:    amr_report -help
VERSION: amr_report -version

% amr_report  -version

% amrfinder --version

```

**Comment by evolarjun** [comment]
So we had been using git tags to set the version in the Makefile automatically. Looking into it I think that doesn't work with bioconda builds because conda just downloads the tarball. I took a look, at the source of prokka, and it looks like you modify a VERSION variable. I was hoping to avoid that kind of thing because I'm absent minded.

I think we'll just have to create a version.txt with every release. That's probably a good impetus to create a release checklist so I don't screw it, or any of the other steps up. Thanks!

**Comment by tseemann** [comment]
Yeah, i forget to increment `$VERSION` all the time :-)

**Comment by evolarjun** [comment]
Fixed by adding a version.txt to the repository. We already had hooks for version.txt in the Makefile so this was trivial to fix. We also put together a release checklist, so hopefully I don't forget to set it too often. 

Thanks again for your feedback Torsten, helpful as always.

**Comment by tseemann** [comment]
No worries @evolarjun - you are doing a great job!
