### ISSUE TITLE
Thoughts on compressed inputs

### ISSUE THREAD

**Issue by rpetit3** [ncbi/amr#61]
Hello! 

What are your thoughts on allowing GZip compressed inputs? Honestly just curious. It's easy enough to uncompress them before running amrfinder+, but as always would be nice to feed the compressed inputs directly to amrfinder+

Thank you!

**Comment by evolarjun** [comment]
With AMRFinderPlus we haven't had much demand for it since the individual files aren't that large.  What are your thoughts about automatic detection? To enable that would slow AMRFinderPlus down (ok, very slightly) for everyone who isn't using gzipped input, but not require three new flags / command line arguments to indicate which input files are gzipped.

Neither blast nor HMMER take gzipped input, though a pipeline can be built that feeds them the data on STDIN. In the low-dependency C++ we're using that requires a little bit of work. If we don't implement that then we're basically gunzipping to a file onto disk to run HMMER and BLAST, and I'm not sure that's much better than someone gunzipping before running AMRFinderPlus. 

In my previous life working with eukaryotic data I also preferred to use gzipped input or utilized software that only had one input file and allowed reading from STDIN so you could pipeline a `zcat`.  So far we've resisted taking the time to implement something like that for AMRFinderPlus because it has 3 input files and we haven't had much demand relative to the effort.

**Comment by rpetit3** [comment]
I think given your reasons, (low demand, additional dependencies, such small inputs), I totally agree with your current approach. `amrfinder+` works great and the split second it takes to uncompress a FASTA is not worth the effort needed to maintain two types of inputs.

As always, thank you very much for your time @evolarjun!
