### ISSUE TITLE
Rename amr_report to amrfinder_report ?

### ISSUE THREAD

**Issue by tseemann** [ncbi/amr#7]
Renaming it would improve consistency
```
amr_report        amrfinder         amrfinder_update
```

Alternatively, use `amrfinder [call | report | update] [options]` syntax?

**Comment by evolarjun** [comment]
That's true amrfinder_report would be more consistent, but we haven't worried about it since amr_report is not intended for public consumption (though you can consume away if you want, it is not documented though).  The only executable other than amrfinder that I would expect end-users to run is amrfinder_update (which can be used to put the data files in their proper place).

**Comment by tseemann** [comment]
It gets installed into global bin/ folder in the conda recipe so I assumed it was for people to use :)
