### ISSUE TITLE
Phenotype specificity?

### ISSUE THREAD

**Issue by schorlton** [ncbi/amr#75]
Thanks  for the great software!

I was wondering about the phenotypic resistance predictions, and if there has been any discussion around listing actual drugs that are predicted to be resistant? I see this is starting to be done in some classes, eg. `AZITHROMYCIN` is listed instead of `MACROLIDES`.

For example, not all beta-lactamases are the same, but as far as I can tell, they're only divided into `BETA-LACTAM`, `CEPHALOSPORIN` and `CARBAPENEM`. It would be really nice if, for example, ESBLs were marked as resistant to all penicillins and cephalosporins up to and including third generation cephalosporins, or if the carbapanemases actually listed resistance to all penicillins, cephalosporins and carbapenems, listing out individual drugs. There's obviously going to be exceptions, like ESBLs vs pip-tazo or amox-clav, or KPC vs ceftaz-avi.

I may totally be missing this in the outputs and DB, but I didn't see it. Anyways, thanks for your consideration!

**Comment by feldgard** [comment]
For some drugs, we use broad classes since a single gene can confer resistance to the entire class (e.g., sulfonamides). When there is available information, we do try to be more specific.

We've held off on being more specific about beta-lactamase subclasses for a few reasons (we have described how we use the classes here: https://github.com/ncbi/amr/wiki/Interpreting-results#class-and-subclass). First, some of the phenotypes can differ in the literature, which presents a problem. Second, there is a compromise between the length of the string used, and the information we want to impart. For some of the beta-lactamases, the list would be very long. There's also the issue that some of these phenotypes are inferred from family membership because they were incompletely tested in the literature (e.g., they never bothered to test 1st generation cephalosporins on that particular allele).

That said, when possible, we do want to provide specific drugs in the subclass field. Are there specific examples that you have in mind (e.g., for KPC-2, the proposed subclass could be "X/Y....")? Also, is there a specific use case for subclass that AMRFinderPlus you have in mind, such as clinical prediction? (I bring this up as an example because there can be a difference between biologically significant activity and resistance _sensu_ CLSI/EUCAST breakpoints).

Thanks,
Mike

**Comment by schorlton** [comment]
Hi Mike,

Thanks for the thoughtful reply. I'll try to address your points in order.

I agree phenotype can differ in the literature, but for big classes (eg. carbapenemases) there is at least some consensus. Did you have a specific example in mind?

I agree the list would be long for some beta-lactamases, but I think this is actually very important to delineate. For clinical, public health, epidemiologic and other purposes, reporting "beta-lactam" resistance is very different than reporting "penicillin" resistance or "piperacillin-tazobactam" resistance. Similarly, if KPC detected, and carbapenem resistance reported, is mero-vabo grouped into carbapenems?

Even using more granular classes would go a long way here, for example, 1st gen cephalosporins, 2nd gen cephalosprins (excluding cephamycins), cephamycins, 3rd gen, etc. Generally (_very_ broad strokes), AMR is shared within these classes and would address your next point. If you wanted to take it a step further, we could maintain a list of class->antimicrobial mappings (CLSI has a list in M100 as a start but it groups all cephalosporins as cephems which isn't helpful for this purpose) and then the user could use this to extrapolate to individual drugs. Interestingly, in Appendix B of the M100 (intrinsic resistance), cephalosporins (+other antimicrobials) are sometimes grouped as I've list above, broken by generation/characteristics.

_However_, this is not always the case, and this is why I think it's actually superior just to store the marker->drug pairs. For example, tetracycline susceptibility usually predicts doxy/minocycline susceptibility, but not vice versa. Same with linezolind/tedizolid. With tetracycline or oxazolidone classes, respectively, you lose this nuance. Ultimately, you will never be able to capture this kind of granularity unless you drill down to drug level, and in doing so it will enable far greater accuracy and usability of AMRFinderPlus' results.

Agree re:difference between detection of marker and CLSI/EUCAST AST...this is complex and won't be solved here. The goal here seems to be to report all AMR markers that increase MIC (or perhaps other markers of resistance, eg. disk diffusion zone size) of bug to drug that aren't seen in a wild-type population. Determining if these affect clinical response is where CLSI/EUCAST come in to set breakpoints.

Thanks again for your consideration and thoughts!

-Sam

**Comment by feldgard** [comment]
Sorry for the very delayed response. We are discussing ways to make the translation to clinical phenotypes easier. We are trying balance comprehensiveness with not misleading users since many of these individual proteins have not been characterized for some or all drugs (e.g., there are 42 tet(M) proteins, many of which are only named by homology). Since we have multiple users with different thresholds of confidence, we tend to err on the conservative side.

Thanks again for your comments. May we contact you in the future if we do make changes to the subclass field?

**Comment by schorlton** [comment]
Thanks for your reply - no worries! Yes, this is obviously a challenging problem to solve for all users. Also happy to contribute if/when you're ready to solicit input.

For sure - I'll shoot you an email off Github so you have my email and we can touch base either offline or here again.

-Sam
