### ISSUE TITLE
future plans for C. auris/Candida spp. support?

### ISSUE THREAD

**Issue by kapsakcj** [ncbi/amr#85]
Hi Arjun et al.,

Curious to see if there are plans in the future for supporting detection of AMR genes and/or point mutations for Candida auris (and potentially other pathogenic Candida species)? e.g. Fluconazole resistance via ERG11 gene 

Curtis

**Comment by evolarjun** [comment]
Hi Curtis,

Because identifying eukaryotic genes requires some slightly different techniques and different database structures we don't have any plans to integrate eukaryotic gene identification into AMRFinderPlus. We have discussed identifying AMR genes in _Candida auris_ and other eukaryotes with a separate tool, but we haven't had time to work on it, and right now we have no concrete plans to do so. It helps us prioritize to know that there is some demand, so thank you for asking.

Thanks,
Arjun

**Comment by kapsakcj** [comment]
Understood, thank you. There is increasing interest among public health labs that are starting to sequence C. auris - I know there are at least a dozen or so PHLs across the US (in addition to the Mycotics Diseases Branch at CDC) that have started or will soon start sequencing this increasingly important pathogen of concern.

I don't have much experience in the mycotics/fungal world, so there may be other tools out there for accomplishing this task but thought I would post here since C. auris is included in the NCBI pathogen detection browser.

Appreciate your quick response! Thank you

**Comment by vbrover** [comment]
We cab actually use AMRFinderPlus if you supply a set of **proteins** of _C. auris_ as input for AMRFinderPlus.
