### ISSUE TITLE
13 non-unique CDS seqs in 2019-04-29.1/AMR_CDS

### ISSUE THREAD

**Issue by tseemann** [ncbi/amr#9]
https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinder/data/2019-04-29.1/AMR_CDS

```
Read 4955, 13 duplicates, wrote 4942.

Non-unique sequence (x2): 1028074076|WP_063838853.1|NG_047213|1|2|aac(
Non-unique sequence (x2): 1105502155|WP_071846307.1|NG_052372|1|2|estX
Non-unique sequence (x2): 1028078994|WP_063839875.1|NG_047214|1|2|ant(
Non-unique sequence (x2): 949780442|WP_057097547.1|NG_062220|1|2|aac(6
Non-unique sequence (x2): 501846383|WP_012655884.1|NG_047217|1|2|aac(6
Non-unique sequence (x2): 1028074075|WP_063838852.1|NG_047210|1|2|aac(
Non-unique sequence (x2): 695264030|WP_032490744.1|NG_047212|1|2|aac(6
Non-unique sequence (x2): 446950888|WP_001028144.1|NG_047055|1|2|aac(6
Non-unique sequence (x2): 1102724732|WP_071593228.1|NG_052052|1|2|catB
Non-unique sequence (x2): 1028078996|WP_063839877.1|NG_047216|1|2|blaO
Non-unique sequence (x2): 1080153693|WP_070342373.1|NG_051910|1|2|ant(
Non-unique sequence (x2): 1509794531|WP_122630840.1|NG_062248|1|2|aac(
Non-unique sequence (x2): 1028078997|WP_063839878.1|NG_047218|1|2|ant(
```

**Comment by evolarjun** [comment]
Those are fusion genes, and because they have two ends doing two different things we used the shortcut of putting the genes in the data file twice with the metadata being different for each one. It is confusing for people parsing the AMRProt and AMR_CDS files. Would it help you for us to release a more normally formatted FASTA file of all the sequences? Also note that AMR_CDS contains just one nucleotide representation for each of the protein sequences, and it may not be the most common one.

The reference gene catalog is the TSV file we intended for public consumption (https://www.ncbi.nlm.nih.gov/pathogens/isolates#/refgene/ or https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/data/latest/ReferenceGeneCatalog.txt), though I can see the value in using the AMRFinder database because the higher level tree hierarchy is not represented in ReferenceGeneCatalog.txt.

**Comment by tseemann** [comment]
If it is a "fusion gene" wouldn't there be only 1 protein and 1 CDS ?
What does fusion mean in this context?

**Comment by evolarjun** [comment]
You are of course correct that fusion genes only have one protein and one sequence, but the function information is double.  What I was inarticulately trying to say in my previous comment is that a fusion gene is a protein with two functional parts each of which has an independent function.  We represent this dual nature imperfectly by reporting two lines in the AMRFinder report, one for each function. The implementation shortcut we took required duplicating the proteins in the database FASTA files so the functional data associated with each could be stored and retrieved in the same way we store functional information for monofunctional proteins.

All that is to say that the duplications are intentional. Bifunctional fusion genes are in the FASTA twice so we can use the defline to store different functional information for each part.
