### ISSUE TITLE
gff3 spec compatibility

### ISSUE THREAD

**Issue by axbazin** [ncbi/amr#91]
Hello,

Thank you for your tool, it is incredibly practical !
There is one cumbersome aspect however, it is the need of a special 'AMRFinder-gff3' format that makes it incompatible with most gff3-generating tools or platforms (Prokka, Rast, Bakta, MicroScope ...) with the exception of refseq gff3.

The [gff3 specifications](https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md) specify that 'ID' should be used as unique identifier while 'Name' should be used as a display name and has no condition of uniqueness whatsoever. It seems that in amrfinder you have followed an opposite rule and chosen to use 'Name' as the unique identifier field.

It would be quite practical to be able to use any gff3 files with your tool without modifying them, like reading 'ID' if 'Name' is not unique or not present, or something equivalent, would retain compatibility with your current behavior, and be quite a time-saver for the futur !

Adelme

**Comment by vbrover** [comment]
Will this help?
https://github.com/ncbi/amr/wiki/Tips-and-tricks#using-prokka-or-RAST-gff-files-with-amrfinderplus

**Comment by evolarjun** [comment]
Hi Adelme,

Thanks for your kind words and the suggestion.

It's something we thought a lot about when we first enabled the combined protein and nucleotide modes for AMRFinderPlus. And I also found the NCBI formats to be annoying :-)   From my perspective it's not the GFF that's the problem, but the FASTA file, since there is a perfectly good ID in the NCBI GFF files, it's unique and fits the requirements of the format, it just doesn't appear in the protein FASTA files that NCBI releases. 

As I'm sure you know there isn't an accepted standard for FASTA IDs, so NCBI created their own standard long before my time. NCBI annotation FASTA files generally just have universal RefSeq accessions as though you had just downloaded individual RefSeq protein sequences, rather than something that is specific to the annotation run. 

I fully understand the frustration of having to write a wrapper or jump through hoops to get AMRFinderPlus to run on your sequences/annotations, it would bug me too except that I'm almost always running AMRFinderPlus on NCBI sequences. As you might have noticed we added an option (`--pgap`) for the output of our annotation pipeline (PGAP) run independently of the internal pipeline.

Would you be willing to send us some examples (GFF + Protein FASTA files) that you encounter frequently so we can think about the best way to handle this in the clearest, most universal, and simplest way because I think you have a good point.

Arjun

**Comment by evolarjun** [comment]
That was very generous and helpful. Thank you!  

We'll take a look and see what we can come up with. 

Arjun

**Comment by evolarjun** [comment]
We've added a `--annotation_format` feature to AMRFinderPlus in [version 3.10.40](https://github.com/ncbi/amr/releases/tag/amrfinder_v3.10.40). The release hasn't yet wound its way through [bioconda](https://anaconda.org/bioconda/ncbi-amrfinderplus), and there are some delays in building the [docker image](https://hub.docker.com/r/ncbi/amr), but that all should be complete by the end of the day. @axbazin please give it a try when you get a chance and let us know if you find any problems.

For details see the [Documentation for the --annotation_format option](https://github.com/evolarjun/amr/wiki/Running-AMRFinderPlus#the---annotation_format-format-option).

Thanks again,
Arjun

**Comment by axbazin** [comment]
Hi,
Thanks a lot for this update, this will make things so much more practical when using annotation tools !
I will test this asap and provide feedback if I find any problem.
Adelme

**Comment by evolarjun** [comment]
Hi @axbazin,

Please do let us know if you have issues. I managed to download and run one or two other examples from each of the data sources / annotation tools you listed to develop and test against, but that's the extent of my experience with most of them, so I'm a little nervous that we made some assumptions based on those examples that don't always hold.

Arjun
